### ISSUE TITLE
Add example for the direct optimization of a unitary gate

### ISSUE THREAD

**Issue by apassenger** [JuliaQuantumControl/GRAPE.jl#24]
I have static and time dependent Hamiltonian and I want to implement X gate to my system. I want to find pulses to implement my unitary. Do you have an example for it? I checked the examples but I could not see an example for implementing a unitary.

Thanks,
Best regards

**Comment by goerz** [comment]
The [perfect-entanglers example](https://juliaquantumcontrol.github.io/GRAPE.jl/stable/examples/perfect_entanglers/) optimizes for a unitary gate. There's two things you'd have to change for a *direct* gate optimization:

1. The Objectives

   You have to set up one objective per basis state, with the basis state as the `initial_state` and the result of applying your target gate to the basis state as the `target_state`. See [the setup for a sqrt-iSWAP gate](https://github.com/ARLQCI/2022-04_semiad_paper/blob/b807ab9d7cfdc139a8e2878b6022bd5827ec7c41/src/run_optimization.jl#L90-L94) from the code for our [Semi-AD paper](https://github.com/ARLQCI/2022-04_semiad_paper#readme) for an "example".

2. The Functional

   Instead of the perfect entanglers functional `J_T_PE`, you want to use the square-modulus functional [`J_T_sm`](https://juliaquantumcontrol.github.io/QuantumControlBase.jl/stable/#QuantumControlBase.Functionals.J_T_sm-Tuple{Any,%20Any}) (or maybe [`J_T_re`](https://juliaquantumcontrol.github.io/QuantumControlBase.jl/stable/#QuantumControlBase.Functionals.J_T_re-Tuple{Any,%20Any}), if you care about the global phase).

In your case, you have a single-qubit gate, so you set up two objectives, one with `initial_state = |0⟩` and `target_state = X̂ |0⟩` and the other with `initial_state = |1⟩` and `target_state = X̂ |1⟩`.

I'll leave this issue open because we definitely *should* have an explicit example for a direct gate optimization in the documentation.
